export const categories = [
    "Electronics",
    "Fashion",
    "Gaming",
    "Home & Garden",
    "Health & Beauty",
    "Sports & Outdoors",
    "Toys & Hobbies",
    "Automotive",
    "Books & Magazines",
    "Music & Movies",
    "Collectibles & Art",
    "Business & Industrial",
    "Real Estate",
    "Food & Beverage",
    "Travel & Experiences",
    "Pets & Animals",
    "Gifts & Flowers",
    "Office Supplies",
    "Jewelry & Watches",
    "Computers & Networking",
    "Mobile Phones & Accessories",
    "Video Games & Consoles",
    "Cameras & Photo",
    "Musical Instruments",
    "Crafts & Sewing",
    "Baby & Kids",
    "Garden & Outdoor",
    "Tools & Home Improvement",
    "Personal Care & Beauty",
    "Fitness & Exercise",
    "Party Supplies & Decorations",
    "Seasonal & Holiday",
    "Collectibles & Memorabilia",
    "Virtual Goods & Services",
    "Tickets & Events",
    "Miscellaneous",
];
