export interface Country {
    name: string;
    flag: string;
    code: string;
    callingCode: string;
}

export type Countries = Record<string, Country>;

export const countries: Countries = {
    ad: {
        name: "Andorra",
        flag: "https://flagcdn.com/ad.svg",
        code: "AD",
        callingCode: "+376",
    },
    ae: {
        name: "United Arab Emirates",
        flag: "https://flagcdn.com/ae.svg",
        code: "AE",
        callingCode: "+971",
    },
    af: {
        name: "Afghanistan",
        flag: "https://flagcdn.com/af.svg",
        code: "AF",
        callingCode: "+93",
    },
    ag: {
        name: "Antigua and Barbuda",
        flag: "https://flagcdn.com/ag.svg",
        code: "AG",
        callingCode: "+1",
    },
    ai: {
        name: "Anguilla",
        flag: "https://flagcdn.com/ai.svg",
        code: "AI",
        callingCode: "+1",
    },
    al: {
        name: "Albania",
        flag: "https://flagcdn.com/al.svg",
        code: "AL",
        callingCode: "+355",
    },
    am: {
        name: "Armenia",
        flag: "https://flagcdn.com/am.svg",
        code: "AM",
        callingCode: "+374",
    },
    ao: {
        name: "Angola",
        flag: "https://flagcdn.com/ao.svg",
        code: "AO",
        callingCode: "+244",
    },
    aq: {
        name: "Antarctica",
        flag: "https://flagcdn.com/aq.svg",
        code: "AQ",
        callingCode: "+672",
    },
    ar: {
        name: "Argentina",
        flag: "https://flagcdn.com/ar.svg",
        code: "AR",
        callingCode: "+54",
    },
    as: {
        name: "American Samoa",
        flag: "https://flagcdn.com/as.svg",
        code: "AS",
        callingCode: "+1",
    },
    at: {
        name: "Austria",
        flag: "https://flagcdn.com/at.svg",
        code: "AT",
        callingCode: "+43",
    },
    au: {
        name: "Australia",
        flag: "https://flagcdn.com/au.svg",
        code: "AU",
        callingCode: "+61",
    },
    aw: {
        name: "Aruba",
        flag: "https://flagcdn.com/aw.svg",
        code: "AW",
        callingCode: "+297",
    },
    ax: {
        name: "Åland Islands",
        flag: "https://flagcdn.com/ax.svg",
        code: "AX",
        callingCode: "+358",
    },
    az: {
        name: "Azerbaijan",
        flag: "https://flagcdn.com/az.svg",
        code: "AZ",
        callingCode: "+994",
    },
    ba: {
        name: "Bosnia and Herzegovina",
        flag: "https://flagcdn.com/ba.svg",
        code: "BA",
        callingCode: "+387",
    },
    bb: {
        name: "Barbados",
        flag: "https://flagcdn.com/bb.svg",
        code: "BB",
        callingCode: "+1",
    },
    bd: {
        name: "Bangladesh",
        flag: "https://flagcdn.com/bd.svg",
        code: "BD",
        callingCode: "+880",
    },
    be: {
        name: "Belgium",
        flag: "https://flagcdn.com/be.svg",
        code: "BE",
        callingCode: "+32",
    },
    bf: {
        name: "Burkina Faso",
        flag: "https://flagcdn.com/bf.svg",
        code: "BF",
        callingCode: "+226",
    },
    bg: {
        name: "Bulgaria",
        flag: "https://flagcdn.com/bg.svg",
        code: "BG",
        callingCode: "+359",
    },
    bh: {
        name: "Bahrain",
        flag: "https://flagcdn.com/bh.svg",
        code: "BH",
        callingCode: "+973",
    },
    bi: {
        name: "Burundi",
        flag: "https://flagcdn.com/bi.svg",
        code: "BI",
        callingCode: "+257",
    },
    bj: {
        name: "Benin",
        flag: "https://flagcdn.com/bj.svg",
        code: "BJ",
        callingCode: "+229",
    },
    bl: {
        name: "Saint Barthélemy",
        flag: "https://flagcdn.com/bl.svg",
        code: "BL",
        callingCode: "+590",
    },
    bm: {
        name: "Bermuda",
        flag: "https://flagcdn.com/bm.svg",
        code: "BM",
        callingCode: "+1",
    },
    bn: {
        name: "Brunei",
        flag: "https://flagcdn.com/bn.svg",
        code: "BN",
        callingCode: "+673",
    },
    bo: {
        name: "Bolivia",
        flag: "https://flagcdn.com/bo.svg",
        code: "BO",
        callingCode: "+591",
    },
    bq: {
        name: "Caribbean Netherlands",
        flag: "https://flagcdn.com/bq.svg",
        code: "BQ",
        callingCode: "+599",
    },
    br: {
        name: "Brazil",
        flag: "https://flagcdn.com/br.svg",
        code: "BR",
        callingCode: "+55",
    },
    bs: {
        name: "Bahamas",
        flag: "https://flagcdn.com/bs.svg",
        code: "BS",
        callingCode: "+1",
    },
    bt: {
        name: "Bhutan",
        flag: "https://flagcdn.com/bt.svg",
        code: "BT",
        callingCode: "+975",
    },
    bw: {
        name: "Botswana",
        flag: "https://flagcdn.com/bw.svg",
        code: "BW",
        callingCode: "+267",
    },
    by: {
        name: "Belarus",
        flag: "https://flagcdn.com/by.svg",
        code: "BY",
        callingCode: "+375",
    },
    bz: {
        name: "Belize",
        flag: "https://flagcdn.com/bz.svg",
        code: "BZ",
        callingCode: "+501",
    },
    ca: {
        name: "Canada",
        flag: "https://flagcdn.com/ca.svg",
        code: "CA",
        callingCode: "+1",
    },
    cc: {
        name: "Cocos (Keeling) Islands",
        flag: "https://flagcdn.com/cc.svg",
        code: "CC",
        callingCode: "+61",
    },
    cd: {
        name: "DR Congo",
        flag: "https://flagcdn.com/cd.svg",
        code: "CD",
        callingCode: "+243",
    },
    cf: {
        name: "Central African Republic",
        flag: "https://flagcdn.com/cf.svg",
        code: "CF",
        callingCode: "+236",
    },
    cg: {
        name: "Republic of the Congo",
        flag: "https://flagcdn.com/cg.svg",
        code: "CG",
        callingCode: "+242",
    },
    ch: {
        name: "Switzerland",
        flag: "https://flagcdn.com/ch.svg",
        code: "CH",
        callingCode: "+41",
    },
    ci: {
        name: "Côte d'Ivoire",
        flag: "https://flagcdn.com/ci.svg",
        code: "CI",
        callingCode: "+225",
    },
    ck: {
        name: "Cook Islands",
        flag: "https://flagcdn.com/ck.svg",
        code: "CK",
        callingCode: "+682",
    },
    cl: {
        name: "Chile",
        flag: "https://flagcdn.com/cl.svg",
        code: "CL",
        callingCode: "+56",
    },
    cm: {
        name: "Cameroon",
        flag: "https://flagcdn.com/cm.svg",
        code: "CM",
        callingCode: "+237",
    },
    cn: {
        name: "China",
        flag: "https://flagcdn.com/cn.svg",
        code: "CN",
        callingCode: "+86",
    },
    co: {
        name: "Colombia",
        flag: "https://flagcdn.com/co.svg",
        code: "CO",
        callingCode: "+57",
    },
    cr: {
        name: "Costa Rica",
        flag: "https://flagcdn.com/cr.svg",
        code: "CR",
        callingCode: "+506",
    },
    cu: {
        name: "Cuba",
        flag: "https://flagcdn.com/cu.svg",
        code: "CU",
        callingCode: "+53",
    },
    cv: {
        name: "Cape Verde",
        flag: "https://flagcdn.com/cv.svg",
        code: "CV",
        callingCode: "+238",
    },
    cw: {
        name: "Curaçao",
        flag: "https://flagcdn.com/cw.svg",
        code: "CW",
        callingCode: "+599",
    },
    cx: {
        name: "Christmas Island",
        flag: "https://flagcdn.com/cx.svg",
        code: "CX",
        callingCode: "+61",
    },
    cy: {
        name: "Cyprus",
        flag: "https://flagcdn.com/cy.svg",
        code: "CY",
        callingCode: "+357",
    },
    cz: {
        name: "Czechia",
        flag: "https://flagcdn.com/cz.svg",
        code: "CZ",
        callingCode: "+420",
    },
    de: {
        name: "Germany",
        flag: "https://flagcdn.com/de.svg",
        code: "DE",
        callingCode: "+49",
    },
    dj: {
        name: "Djibouti",
        flag: "https://flagcdn.com/dj.svg",
        code: "DJ",
        callingCode: "+253",
    },
    dk: {
        name: "Denmark",
        flag: "https://flagcdn.com/dk.svg",
        code: "DK",
        callingCode: "+45",
    },
    dm: {
        name: "Dominica",
        flag: "https://flagcdn.com/dm.svg",
        code: "DM",
        callingCode: "+1",
    },
    do: {
        name: "Dominican Republic",
        flag: "https://flagcdn.com/do.svg",
        code: "DO",
        callingCode: "+1",
    },
    dz: {
        name: "Algeria",
        flag: "https://flagcdn.com/dz.svg",
        code: "DZ",
        callingCode: "+213",
    },
    ec: {
        name: "Ecuador",
        flag: "https://flagcdn.com/ec.svg",
        code: "EC",
        callingCode: "+593",
    },
    ee: {
        name: "Estonia",
        flag: "https://flagcdn.com/ee.svg",
        code: "EE",
        callingCode: "+372",
    },
    eg: {
        name: "Egypt",
        flag: "https://flagcdn.com/eg.svg",
        code: "EG",
        callingCode: "+20",
    },
    eh: {
        name: "Western Sahara",
        flag: "https://flagcdn.com/eh.svg",
        code: "EH",
        callingCode: "+212",
    },
    er: {
        name: "Eritrea",
        flag: "https://flagcdn.com/er.svg",
        code: "ER",
        callingCode: "+291",
    },
    es: {
        name: "Spain",
        flag: "https://flagcdn.com/es.svg",
        code: "ES",
        callingCode: "+34",
    },
    et: {
        name: "Ethiopia",
        flag: "https://flagcdn.com/et.svg",
        code: "ET",
        callingCode: "+251",
    },
    fi: {
        name: "Finland",
        flag: "https://flagcdn.com/fi.svg",
        code: "FI",
        callingCode: "+358",
    },
    fj: {
        name: "Fiji",
        flag: "https://flagcdn.com/fj.svg",
        code: "FJ",
        callingCode: "+679",
    },
    fk: {
        name: "Falkland Islands",
        flag: "https://flagcdn.com/fk.svg",
        code: "FK",
        callingCode: "+500",
    },
    fm: {
        name: "Micronesia",
        flag: "https://flagcdn.com/fm.svg",
        code: "FM",
        callingCode: "+691",
    },
    fo: {
        name: "Faroe Islands",
        flag: "https://flagcdn.com/fo.svg",
        code: "FO",
        callingCode: "+298",
    },
    fr: {
        name: "France",
        flag: "https://flagcdn.com/fr.svg",
        code: "FR",
        callingCode: "+33",
    },
    ga: {
        name: "Gabon",
        flag: "https://flagcdn.com/ga.svg",
        code: "GA",
        callingCode: "+241",
    },
    gb: {
        name: "United Kingdom",
        flag: "https://flagcdn.com/gb.svg",
        code: "GB",
        callingCode: "+44",
    },
    gd: {
        name: "Grenada",
        flag: "https://flagcdn.com/gd.svg",
        code: "GD",
        callingCode: "+1",
    },
    ge: {
        name: "Georgia",
        flag: "https://flagcdn.com/ge.svg",
        code: "GE",
        callingCode: "+995",
    },
    gf: {
        name: "French Guiana",
        flag: "https://flagcdn.com/gf.svg",
        code: "GF",
        callingCode: "+594",
    },
    gg: {
        name: "Guernsey",
        flag: "https://flagcdn.com/gg.svg",
        code: "GG",
        callingCode: "+44",
    },
    gh: {
        name: "Ghana",
        flag: "https://flagcdn.com/gh.svg",
        code: "GH",
        callingCode: "+233",
    },
    gi: {
        name: "Gibraltar",
        flag: "https://flagcdn.com/gi.svg",
        code: "GI",
        callingCode: "+350",
    },
    gl: {
        name: "Greenland",
        flag: "https://flagcdn.com/gl.svg",
        code: "GL",
        callingCode: "+299",
    },
    gm: {
        name: "Gambia",
        flag: "https://flagcdn.com/gm.svg",
        code: "GM",
        callingCode: "+220",
    },
    gn: {
        name: "Guinea",
        flag: "https://flagcdn.com/gn.svg",
        code: "GN",
        callingCode: "+224",
    },
    gp: {
        name: "Guadeloupe",
        flag: "https://flagcdn.com/gp.svg",
        code: "GP",
        callingCode: "+590",
    },
    gq: {
        name: "Equatorial Guinea",
        flag: "https://flagcdn.com/gq.svg",
        code: "GQ",
        callingCode: "+240",
    },
    gr: {
        name: "Greece",
        flag: "https://flagcdn.com/gr.svg",
        code: "GR",
        callingCode: "+30",
    },
    gs: {
        name: "South Georgia",
        flag: "https://flagcdn.com/gs.svg",
        code: "GS",
        callingCode: "+500",
    },
    gt: {
        name: "Guatemala",
        flag: "https://flagcdn.com/gt.svg",
        code: "GT",
        callingCode: "+502",
    },
    gu: {
        name: "Guam",
        flag: "https://flagcdn.com/gu.svg",
        code: "GU",
        callingCode: "+1",
    },
    gw: {
        name: "Guinea-Bissau",
        flag: "https://flagcdn.com/gw.svg",
        code: "GW",
        callingCode: "+245",
    },
    gy: {
        name: "Guyana",
        flag: "https://flagcdn.com/gy.svg",
        code: "GY",
        callingCode: "+592",
    },
    hk: {
        name: "Hong Kong",
        flag: "https://flagcdn.com/hk.svg",
        code: "HK",
        callingCode: "+852",
    },
    hn: {
        name: "Honduras",
        flag: "https://flagcdn.com/hn.svg",
        code: "HN",
        callingCode: "+504",
    },
    hr: {
        name: "Croatia",
        flag: "https://flagcdn.com/hr.svg",
        code: "HR",
        callingCode: "+385",
    },
    ht: {
        name: "Haiti",
        flag: "https://flagcdn.com/ht.svg",
        code: "HT",
        callingCode: "+509",
    },
    hu: {
        name: "Hungary",
        flag: "https://flagcdn.com/hu.svg",
        code: "HU",
        callingCode: "+36",
    },
    id: {
        name: "Indonesia",
        flag: "https://flagcdn.com/id.svg",
        code: "ID",
        callingCode: "+62",
    },
    ie: {
        name: "Ireland",
        flag: "https://flagcdn.com/ie.svg",
        code: "IE",
        callingCode: "+353",
    },
    il: {
        name: "Israel",
        flag: "https://flagcdn.com/il.svg",
        code: "IL",
        callingCode: "+972",
    },
    im: {
        name: "Isle of Man",
        flag: "https://flagcdn.com/im.svg",
        code: "IM",
        callingCode: "+44",
    },
    in: {
        name: "India",
        flag: "https://flagcdn.com/in.svg",
        code: "IN",
        callingCode: "+91",
    },
    io: {
        name: "British Indian Ocean Territory",
        flag: "https://flagcdn.com/io.svg",
        code: "IO",
        callingCode: "+246",
    },
    iq: {
        name: "Iraq",
        flag: "https://flagcdn.com/iq.svg",
        code: "IQ",
        callingCode: "+964",
    },
    ir: {
        name: "Iran",
        flag: "https://flagcdn.com/ir.svg",
        code: "IR",
        callingCode: "+98",
    },
    is: {
        name: "Iceland",
        flag: "https://flagcdn.com/is.svg",
        code: "IS",
        callingCode: "+354",
    },
    it: {
        name: "Italy",
        flag: "https://flagcdn.com/it.svg",
        code: "IT",
        callingCode: "+39",
    },
    je: {
        name: "Jersey",
        flag: "https://flagcdn.com/je.svg",
        code: "JE",
        callingCode: "+44",
    },
    jm: {
        name: "Jamaica",
        flag: "https://flagcdn.com/jm.svg",
        code: "JM",
        callingCode: "+1",
    },
    jo: {
        name: "Jordan",
        flag: "https://flagcdn.com/jo.svg",
        code: "JO",
        callingCode: "+962",
    },
    jp: {
        name: "Japan",
        flag: "https://flagcdn.com/jp.svg",
        code: "JP",
        callingCode: "+81",
    },
    ke: {
        name: "Kenya",
        flag: "https://flagcdn.com/ke.svg",
        code: "KE",
        callingCode: "+254",
    },
    kg: {
        name: "Kyrgyzstan",
        flag: "https://flagcdn.com/kg.svg",
        code: "KG",
        callingCode: "+996",
    },
    kh: {
        name: "Cambodia",
        flag: "https://flagcdn.com/kh.svg",
        code: "KH",
        callingCode: "+855",
    },
    ki: {
        name: "Kiribati",
        flag: "https://flagcdn.com/ki.svg",
        code: "KI",
        callingCode: "+686",
    },
    km: {
        name: "Comoros",
        flag: "https://flagcdn.com/km.svg",
        code: "KM",
        callingCode: "+269",
    },
    kn: {
        name: "Saint Kitts and Nevis",
        flag: "https://flagcdn.com/kn.svg",
        code: "KN",
        callingCode: "+1",
    },
    kp: {
        name: "North Korea",
        flag: "https://flagcdn.com/kp.svg",
        code: "KP",
        callingCode: "+850",
    },
    kr: {
        name: "South Korea",
        flag: "https://flagcdn.com/kr.svg",
        code: "KR",
        callingCode: "+82",
    },
    kw: {
        name: "Kuwait",
        flag: "https://flagcdn.com/kw.svg",
        code: "KW",
        callingCode: "+965",
    },
    ky: {
        name: "Cayman Islands",
        flag: "https://flagcdn.com/ky.svg",
        code: "KY",
        callingCode: "+1",
    },
    kz: {
        name: "Kazakhstan",
        flag: "https://flagcdn.com/kz.svg",
        code: "KZ",
        callingCode: "+7",
    },
    la: {
        name: "Laos",
        flag: "https://flagcdn.com/la.svg",
        code: "LA",
        callingCode: "+856",
    },
    lb: {
        name: "Lebanon",
        flag: "https://flagcdn.com/lb.svg",
        code: "LB",
        callingCode: "+961",
    },
    lc: {
        name: "Saint Lucia",
        flag: "https://flagcdn.com/lc.svg",
        code: "LC",
        callingCode: "+1",
    },
    li: {
        name: "Liechtenstein",
        flag: "https://flagcdn.com/li.svg",
        code: "LI",
        callingCode: "+423",
    },
    lk: {
        name: "Sri Lanka",
        flag: "https://flagcdn.com/lk.svg",
        code: "LK",
        callingCode: "+94",
    },
    lr: {
        name: "Liberia",
        flag: "https://flagcdn.com/lr.svg",
        code: "LR",
        callingCode: "+231",
    },
    ls: {
        name: "Lesotho",
        flag: "https://flagcdn.com/ls.svg",
        code: "LS",
        callingCode: "+266",
    },
    lt: {
        name: "Lithuania",
        flag: "https://flagcdn.com/lt.svg",
        code: "LT",
        callingCode: "+370",
    },
    lu: {
        name: "Luxembourg",
        flag: "https://flagcdn.com/lu.svg",
        code: "LU",
        callingCode: "+352",
    },
    lv: {
        name: "Latvia",
        flag: "https://flagcdn.com/lv.svg",
        code: "LV",
        callingCode: "+371",
    },
    ly: {
        name: "Libya",
        flag: "https://flagcdn.com/ly.svg",
        code: "LY",
        callingCode: "+218",
    },
    ma: {
        name: "Morocco",
        flag: "https://flagcdn.com/ma.svg",
        code: "MA",
        callingCode: "+212",
    },
    mc: {
        name: "Monaco",
        flag: "https://flagcdn.com/mc.svg",
        code: "MC",
        callingCode: "+377",
    },
    md: {
        name: "Moldova",
        flag: "https://flagcdn.com/md.svg",
        code: "MD",
        callingCode: "+373",
    },
    me: {
        name: "Montenegro",
        flag: "https://flagcdn.com/me.svg",
        code: "ME",
        callingCode: "+382",
    },
    mf: {
        name: "Saint Martin",
        flag: "https://flagcdn.com/mf.svg",
        code: "MF",
        callingCode: "+590",
    },
    mg: {
        name: "Madagascar",
        flag: "https://flagcdn.com/mg.svg",
        code: "MG",
        callingCode: "+261",
    },
    mh: {
        name: "Marshall Islands",
        flag: "https://flagcdn.com/mh.svg",
        code: "MH",
        callingCode: "+692",
    },
    mk: {
        name: "North Macedonia",
        flag: "https://flagcdn.com/mk.svg",
        code: "MK",
        callingCode: "+389",
    },
    ml: {
        name: "Mali",
        flag: "https://flagcdn.com/ml.svg",
        code: "ML",
        callingCode: "+223",
    },
    mm: {
        name: "Myanmar",
        flag: "https://flagcdn.com/mm.svg",
        code: "MM",
        callingCode: "+95",
    },
    mn: {
        name: "Mongolia",
        flag: "https://flagcdn.com/mn.svg",
        code: "MN",
        callingCode: "+976",
    },
    mo: {
        name: "Macau",
        flag: "https://flagcdn.com/mo.svg",
        code: "MO",
        callingCode: "+853",
    },
    mp: {
        name: "Northern Mariana Islands",
        flag: "https://flagcdn.com/mp.svg",
        code: "MP",
        callingCode: "+1",
    },
    mq: {
        name: "Martinique",
        flag: "https://flagcdn.com/mq.svg",
        code: "MQ",
        callingCode: "+596",
    },
    mr: {
        name: "Mauritania",
        flag: "https://flagcdn.com/mr.svg",
        code: "MR",
        callingCode: "+222",
    },
    ms: {
        name: "Montserrat",
        flag: "https://flagcdn.com/ms.svg",
        code: "MS",
        callingCode: "+1",
    },
    mt: {
        name: "Malta",
        flag: "https://flagcdn.com/mt.svg",
        code: "MT",
        callingCode: "+356",
    },
    mu: {
        name: "Mauritius",
        flag: "https://flagcdn.com/mu.svg",
        code: "MU",
        callingCode: "+230",
    },
    mv: {
        name: "Maldives",
        flag: "https://flagcdn.com/mv.svg",
        code: "MV",
        callingCode: "+960",
    },
    mw: {
        name: "Malawi",
        flag: "https://flagcdn.com/mw.svg",
        code: "MW",
        callingCode: "+265",
    },
    mx: {
        name: "Mexico",
        flag: "https://flagcdn.com/mx.svg",
        code: "MX",
        callingCode: "+52",
    },
    my: {
        name: "Malaysia",
        flag: "https://flagcdn.com/my.svg",
        code: "MY",
        callingCode: "+60",
    },
    mz: {
        name: "Mozambique",
        flag: "https://flagcdn.com/mz.svg",
        code: "MZ",
        callingCode: "+258",
    },
    na: {
        name: "Namibia",
        flag: "https://flagcdn.com/na.svg",
        code: "NA",
        callingCode: "+264",
    },
    nc: {
        name: "New Caledonia",
        flag: "https://flagcdn.com/nc.svg",
        code: "NC",
        callingCode: "+687",
    },
    ne: {
        name: "Niger",
        flag: "https://flagcdn.com/ne.svg",
        code: "NE",
        callingCode: "+227",
    },
    nf: {
        name: "Norfolk Island",
        flag: "https://flagcdn.com/nf.svg",
        code: "NF",
        callingCode: "+672",
    },
    ng: {
        name: "Nigeria",
        flag: "https://flagcdn.com/ng.svg",
        code: "NG",
        callingCode: "+234",
    },
    ni: {
        name: "Nicaragua",
        flag: "https://flagcdn.com/ni.svg",
        code: "NI",
        callingCode: "+505",
    },
    nl: {
        name: "Netherlands",
        flag: "https://flagcdn.com/nl.svg",
        code: "NL",
        callingCode: "+31",
    },
    no: {
        name: "Norway",
        flag: "https://flagcdn.com/no.svg",
        code: "NO",
        callingCode: "+47",
    },
    np: {
        name: "Nepal",
        flag: "https://flagcdn.com/np.svg",
        code: "NP",
        callingCode: "+977",
    },
    nr: {
        name: "Nauru",
        flag: "https://flagcdn.com/nr.svg",
        code: "NR",
        callingCode: "+674",
    },
    nu: {
        name: "Niue",
        flag: "https://flagcdn.com/nu.svg",
        code: "NU",
        callingCode: "+683",
    },
    nz: {
        name: "New Zealand",
        flag: "https://flagcdn.com/nz.svg",
        code: "NZ",
        callingCode: "+64",
    },
    om: {
        name: "Oman",
        flag: "https://flagcdn.com/om.svg",
        code: "OM",
        callingCode: "+968",
    },
    pa: {
        name: "Panama",
        flag: "https://flagcdn.com/pa.svg",
        code: "PA",
        callingCode: "+507",
    },
    pe: {
        name: "Peru",
        flag: "https://flagcdn.com/pe.svg",
        code: "PE",
        callingCode: "+51",
    },
    pf: {
        name: "French Polynesia",
        flag: "https://flagcdn.com/pf.svg",
        code: "PF",
        callingCode: "+689",
    },
    pg: {
        name: "Papua New Guinea",
        flag: "https://flagcdn.com/pg.svg",
        code: "PG",
        callingCode: "+675",
    },
    ph: {
        name: "Philippines",
        flag: "https://flagcdn.com/ph.svg",
        code: "PH",
        callingCode: "+63",
    },
    pk: {
        name: "Pakistan",
        flag: "https://flagcdn.com/pk.svg",
        code: "PK",
        callingCode: "+92",
    },
    pl: {
        name: "Poland",
        flag: "https://flagcdn.com/pl.svg",
        code: "PL",
        callingCode: "+48",
    },
    pm: {
        name: "Saint Pierre and Miquelon",
        flag: "https://flagcdn.com/pm.svg",
        code: "PM",
        callingCode: "+508",
    },
    pn: {
        name: "Pitcairn Islands",
        flag: "https://flagcdn.com/pn.svg",
        code: "PN",
        callingCode: "+64",
    },
    pr: {
        name: "Puerto Rico",
        flag: "https://flagcdn.com/pr.svg",
        code: "PR",
        callingCode: "+1",
    },
    ps: {
        name: "Palestine",
        flag: "https://flagcdn.com/ps.svg",
        code: "PS",
        callingCode: "+970",
    },
    pt: {
        name: "Portugal",
        flag: "https://flagcdn.com/pt.svg",
        code: "PT",
        callingCode: "+351",
    },
    pw: {
        name: "Palau",
        flag: "https://flagcdn.com/pw.svg",
        code: "PW",
        callingCode: "+680",
    },
    py: {
        name: "Paraguay",
        flag: "https://flagcdn.com/py.svg",
        code: "PY",
        callingCode: "+595",
    },
    qa: {
        name: "Qatar",
        flag: "https://flagcdn.com/qa.svg",
        code: "QA",
        callingCode: "+974",
    },
    re: {
        name: "Réunion",
        flag: "https://flagcdn.com/re.svg",
        code: "RE",
        callingCode: "+262",
    },
    ro: {
        name: "Romania",
        flag: "https://flagcdn.com/ro.svg",
        code: "RO",
        callingCode: "+40",
    },
    rs: {
        name: "Serbia",
        flag: "https://flagcdn.com/rs.svg",
        code: "RS",
        callingCode: "+381",
    },
    ru: {
        name: "Russia",
        flag: "https://flagcdn.com/ru.svg",
        code: "RU",
        callingCode: "+7",
    },
    rw: {
        name: "Rwanda",
        flag: "https://flagcdn.com/rw.svg",
        code: "RW",
        callingCode: "+250",
    },
    sa: {
        name: "Saudi Arabia",
        flag: "https://flagcdn.com/sa.svg",
        code: "SA",
        callingCode: "+966",
    },
    sb: {
        name: "Solomon Islands",
        flag: "https://flagcdn.com/sb.svg",
        code: "SB",
        callingCode: "+677",
    },
    sc: {
        name: "Seychelles",
        flag: "https://flagcdn.com/sc.svg",
        code: "SC",
        callingCode: "+248",
    },
    sd: {
        name: "Sudan",
        flag: "https://flagcdn.com/sd.svg",
        code: "SD",
        callingCode: "+249",
    },
    se: {
        name: "Sweden",
        flag: "https://flagcdn.com/se.svg",
        code: "SE",
        callingCode: "+46",
    },
    sg: {
        name: "Singapore",
        flag: "https://flagcdn.com/sg.svg",
        code: "SG",
        callingCode: "+65",
    },
    sh: {
        name: "Saint Helena, Ascension and Tristan da Cunha",
        flag: "https://flagcdn.com/sh.svg",
        code: "SH",
        callingCode: "+290",
    },
    si: {
        name: "Slovenia",
        flag: "https://flagcdn.com/si.svg",
        code: "SI",
        callingCode: "+386",
    },
    sj: {
        name: "Svalbard and Jan Mayen",
        flag: "https://flagcdn.com/sj.svg",
        code: "SJ",
        callingCode: "+47",
    },
    sk: {
        name: "Slovakia",
        flag: "https://flagcdn.com/sk.svg",
        code: "SK",
        callingCode: "+421",
    },
    sl: {
        name: "Sierra Leone",
        flag: "https://flagcdn.com/sl.svg",
        code: "SL",
        callingCode: "+232",
    },
    sm: {
        name: "San Marino",
        flag: "https://flagcdn.com/sm.svg",
        code: "SM",
        callingCode: "+378",
    },
    sn: {
        name: "Senegal",
        flag: "https://flagcdn.com/sn.svg",
        code: "SN",
        callingCode: "+221",
    },
    so: {
        name: "Somalia",
        flag: "https://flagcdn.com/so.svg",
        code: "SO",
        callingCode: "+252",
    },
    sr: {
        name: "Suriname",
        flag: "https://flagcdn.com/sr.svg",
        code: "SR",
        callingCode: "+597",
    },
    ss: {
        name: "South Sudan",
        flag: "https://flagcdn.com/ss.svg",
        code: "SS",
        callingCode: "+211",
    },
    st: {
        name: "São Tomé and Príncipe",
        flag: "https://flagcdn.com/st.svg",
        code: "ST",
        callingCode: "+239",
    },
    sv: {
        name: "El Salvador",
        flag: "https://flagcdn.com/sv.svg",
        code: "SV",
        callingCode: "+503",
    },
    sx: {
        name: "Sint Maarten",
        flag: "https://flagcdn.com/sx.svg",
        code: "SX",
        callingCode: "+1",
    },
    sy: {
        name: "Syria",
        flag: "https://flagcdn.com/sy.svg",
        code: "SY",
        callingCode: "+963",
    },
    sz: {
        name: "Eswatini (Swaziland)",
        flag: "https://flagcdn.com/sz.svg",
        code: "SZ",
        callingCode: "+268",
    },
    tc: {
        name: "Turks and Caicos Islands",
        flag: "https://flagcdn.com/tc.svg",
        code: "TC",
        callingCode: "+1",
    },
    td: {
        name: "Chad",
        flag: "https://flagcdn.com/td.svg",
        code: "TD",
        callingCode: "+235",
    },
    tf: {
        name: "French Southern and Antarctic Lands",
        flag: "https://flagcdn.com/tf.svg",
        code: "TF",
        callingCode: "+262",
    },
    tg: {
        name: "Togo",
        flag: "https://flagcdn.com/tg.svg",
        code: "TG",
        callingCode: "+228",
    },
    th: {
        name: "Thailand",
        flag: "https://flagcdn.com/th.svg",
        code: "TH",
        callingCode: "+66",
    },
    tj: {
        name: "Tajikistan",
        flag: "https://flagcdn.com/tj.svg",
        code: "TJ",
        callingCode: "+992",
    },
    tk: {
        name: "Tokelau",
        flag: "https://flagcdn.com/tk.svg",
        code: "TK",
        callingCode: "+690",
    },
    tl: {
        name: "Timor-Leste",
        flag: "https://flagcdn.com/tl.svg",
        code: "TL",
        callingCode: "+670",
    },
    tm: {
        name: "Turkmenistan",
        flag: "https://flagcdn.com/tm.svg",
        code: "TM",
        callingCode: "+993",
    },
    tn: {
        name: "Tunisia",
        flag: "https://flagcdn.com/tn.svg",
        code: "TN",
        callingCode: "+216",
    },
    to: {
        name: "Tonga",
        flag: "https://flagcdn.com/to.svg",
        code: "TO",
        callingCode: "+676",
    },
    tr: {
        name: "Turkey",
        flag: "https://flagcdn.com/tr.svg",
        code: "TR",
        callingCode: "+90",
    },
    tt: {
        name: "Trinidad and Tobago",
        flag: "https://flagcdn.com/tt.svg",
        code: "TT",
        callingCode: "+1",
    },
    tv: {
        name: "Tuvalu",
        flag: "https://flagcdn.com/tv.svg",
        code: "TV",
        callingCode: "+688",
    },
    tw: {
        name: "Taiwan",
        flag: "https://flagcdn.com/tw.svg",
        code: "TW",
        callingCode: "+886",
    },
    tz: {
        name: "Tanzania",
        flag: "https://flagcdn.com/tz.svg",
        code: "TZ",
        callingCode: "+255",
    },
    ua: {
        name: "Ukraine",
        flag: "https://flagcdn.com/ua.svg",
        code: "UA",
        callingCode: "+380",
    },
    ug: {
        name: "Uganda",
        flag: "https://flagcdn.com/ug.svg",
        code: "UG",
        callingCode: "+256",
    },
    us: {
        name: "United States",
        flag: "https://flagcdn.com/us.svg",
        code: "US",
        callingCode: "+1",
    },
    uy: {
        name: "Uruguay",
        flag: "https://flagcdn.com/uy.svg",
        code: "UY",
        callingCode: "+598",
    },
    uz: {
        name: "Uzbekistan",
        flag: "https://flagcdn.com/uz.svg",
        code: "UZ",
        callingCode: "+998",
    },
    va: {
        name: "Vatican City (Holy See)",
        flag: "https://flagcdn.com/va.svg",
        code: "VA",
        callingCode: "+379",
    },
    vc: {
        name: "Saint Vincent and the Grenadines",
        flag: "https://flagcdn.com/vc.svg",
        code: "VC",
        callingCode: "+1",
    },
    ve: {
        name: "Venezuela",
        flag: "https://flagcdn.com/ve.svg",
        code: "VE",
        callingCode: "+58",
    },
    vg: {
        name: "British Virgin Islands",
        flag: "https://flagcdn.com/vg.svg",
        code: "VG",
        callingCode: "+1",
    },
    vi: {
        name: "United States Virgin Islands",
        flag: "https://flagcdn.com/vi.svg",
        code: "VI",
        callingCode: "+1",
    },
    vn: {
        name: "Vietnam",
        flag: "https://flagcdn.com/vn.svg",
        code: "VN",
        callingCode: "+84",
    },
    vu: {
        name: "Vanuatu",
        flag: "https://flagcdn.com/vu.svg",
        code: "VU",
        callingCode: "+678",
    },
    wf: {
        name: "Wallis and Futuna",
        flag: "https://flagcdn.com/wf.svg",
        code: "WF",
        callingCode: "+681",
    },
    ws: {
        name: "Samoa",
        flag: "https://flagcdn.com/ws.svg",
        code: "WS",
        callingCode: "+685",
    },
    xk: {
        name: "Kosovo",
        flag: "https://flagcdn.com/xk.svg",
        code: "XK",
        callingCode: "+383",
    },
    ye: {
        name: "Yemen",
        flag: "https://flagcdn.com/ye.svg",
        code: "YE",
        callingCode: "+967",
    },
    yt: {
        name: "Mayotte",
        flag: "https://flagcdn.com/yt.svg",
        code: "YT",
        callingCode: "+262",
    },
    za: {
        name: "South Africa",
        flag: "https://flagcdn.com/za.svg",
        code: "ZA",
        callingCode: "+27",
    },
    zm: {
        name: "Zambia",
        flag: "https://flagcdn.com/zm.svg",
        code: "ZM",
        callingCode: "+260",
    },
    zw: {
        name: "Zimbabwe",
        flag: "https://flagcdn.com/zw.svg",
        code: "ZW",
        callingCode: "+263",
    },
};

// Convert the countries object to an array for easier use in the component
export const COUNTRIES = Object.values(countries).sort((a, b) =>
    a.name.localeCompare(b.name)
);

// Helper function to find country by code
export const findCountryByCode = (code: string): Country | undefined => {
    return COUNTRIES.find((country) => country.code === code.toUpperCase());
};

// Helper function to find country by calling code
export const findCountryByCallingCode = (
    callingCode: string
): Country | undefined => {
    // Remove the + if it exists
    const cleanCallingCode = callingCode.startsWith("+")
        ? callingCode
        : `+${callingCode}`;
    return COUNTRIES.find(
        (country) => country.callingCode === cleanCallingCode
    );
};
